# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IDB' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IDB
    pod 'Alamofire', '~> 4.5’
    pod 'XLPagerTabStrip', '~> 8.0'

  target 'IDBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IDBUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
